src/Entity/Stock.php
<?php

namespace App\Entity;

use App\Repository\StockRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: StockRepository::class)]
class Stock
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(
        min: 2,
        max: 20,
        minMessage: 'Your product name must be at least {{ limit }} characters long',
        maxMessage: 'Your product name cannot be longer than {{ limit }} characters',
    )]
    private ?string $nomProduit = null;

    #[ORM\Column(nullable: true)]
    private ?int $quantite_entre = null;

    #[ORM\Column(nullable: true)]
    private ?int $quantite_sortie = null;

    #[ORM\Column(nullable: true)]
    private ?int $quantite_restante = null;

    #[ORM\Column(type: "date", nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'stocks')]
    private ?Fournisseur $fournisseur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nomProduit;
    }
    
    public function setNomProduit(?string $nomProduit): self
    {
        $this->nomProduit = $nomProduit;
    
        return $this;
    }

    public function __toString()
    {
        return $this->id;
    }
    
    public function getQuantiteEntre(): ?int
    {
        return $this->quantite_entre;
    }

    public function setQuantiteEntre(?int $quantite_entre): self
    {
        $this->quantite_entre = $quantite_entre;

        return $this;
    }

    public function getQuantiteSortie(): ?int
    {
        return $this->quantite_sortie;
    }

    public function setQuantiteSortie(?int $quantite_sortie): self
    {
        $this->quantite_sortie = $quantite_sortie;

        return $this;
    }

    public function getQuantiteRestante(): ?int
    {
        return $this->quantite_restante;
    }

    public function setQuantiteRestante(?int $quantite_restante): self
    {
        $this->quantite_restante = $quantite_restante;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getFournisseur(): ?Fournisseur
    {
        return $this->fournisseur;
    }

    public function setFournisseur(?Fournisseur $fournisseur): self
    {
        $this->fournisseur = $fournisseur;

        return $this;
    }

}

src/Form/StockType.php
<?php

namespace App\Form;

use App\Entity\Stock;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Fournisseur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType as DoctrineEntityType;
use Symfony\Component\Validator\Constraints\Length; 

class StockType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_produit', TextType::class, [
                'label' => 'Product Name',
                'attr' => ['placeholder' => 'Enter the product name'], // Example: Adding a placeholder
                'constraints' => [
                  
                    new Length([
                        'min' => 1,
                        'max' => 255,
                        'minMessage' => 'Product name must be at least {{ limit }} character long',
                        'maxMessage' => 'Product name cannot be longer than {{ limit }} characters',
                    ]),
                ],
            ])
            ->add('quantite_entre', IntegerType::class, [
                'label' => 'Quantity In',
                'attr' => ['placeholder' => 'Enter the quantity in'],
            ])
            ->add('quantite_sortie', IntegerType::class, [
                'label' => 'Quantity Out',
                'attr' => ['placeholder' => 'Enter the quantity out'],
            ])
            ->add('quantite_restante', IntegerType::class, [
                'label' => 'Remaining Quantity',
                'attr' => ['placeholder' => 'Enter the remaining quantity'],
            ])
            ->add('date', DateType::class, [
                'label' => 'Date',
                'widget' => 'single_text', // Example: Render the date as a single text input
                'attr' => ['placeholder' => 'Select the date'],
            ])
            ->add('fournisseur', DoctrineEntityType::class, [
                'label' => 'Supplier',
                'class' => Fournisseur::class,
                'choice_label' => function ($fournisseur) {
                    return $fournisseur->getNom() . ' ' . $fournisseur->getPrenom();
                },
                'attr' => ['class' => 'form-select'], // Example: Adding a CSS class to the select input
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Stock::class,
        ]);
    }
}

src/Controller/StockController.php
<?php

namespace App\Controller;

use App\Entity\Stock;
use App\Form\StockType;
use App\Repository\StockRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


#[Route('/stock')]
class StockController extends AbstractController
{


    #[Route('/new', name: 'stock_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,StockRepository $stockRepository): Response
    {
        $stock = new Stock();
        $form = $this->createForm(StockType::class, $stock);
        $form->handleRequest($request);
        $requestString = $request->get('searchValue');
        $stockSearch = $stockRepository->findAdmin($requestString);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($stock);
            $entityManager->flush();

        
        }

        return $this->renderForm('stock/index.html.twig', [
            'stock' => $stock,
            "stockSearch" => $stockSearch,

            'form' => $form, 
            'stocks' => $stockRepository->findAll()
        ]);
    }


    #[Route('/{id}', name: 'stock_show', methods: ['GET'])]
    public function show(Stock $stock): Response
    {
        return $this->render('stock/show.html.twig', [
            'stock' => $stock,
        ]);
    }

    #[Route('/{id}/edit', name: 'stock_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Stock $stock, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StockType::class, $stock);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('stock_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('stock/edit.html.twig', [
            'stock' => $stock,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'stock_delete', methods: ['POST'])]
    public function delete(Request $request, Stock $stock, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$stock->getId(), $request->request->get('_token'))) {
            $entityManager->remove($stock);
            $entityManager->flush();
        }

        return $this->redirectToRoute('stock_new', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/new/{order}', name: 'ASC', methods: ['GET'])]
public function ASC(Request $request, EntityManagerInterface $entityManager, StockRepository $stockRepository, string $order): Response
{
    $stock = new Stock();
    $form = $this->createForm(StockType::class, $stock);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager->persist($stock);
        $entityManager->flush();
    }

    // Use the custom query method from the repository
    $stocks = $stockRepository->orderByNom($order);

    return $this->renderForm('stock/index.html.twig', [
        'stock' => $stock,
        'form' => $form,
        
    ]);
}



   
    
       }

templates/stock/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Edit Stock{% endblock %}

{% block body %}
    <h1>Edit Stock</h1>

    {{ include('stock/new.html.twig', {'button_label': 'Update'}) }}


{% endblock %}

templates/stock/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Stock Index
{% endblock %}

{% block body %}

	<main id="main" class="main">

		<div class="pagetitle">
			<h1>Stock Tables</h1>
			<nav>
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="index.html">Home</a>
					</li>
					<li class="breadcrumb-item">Tables</li>
					<li class="breadcrumb-item active">Stock</li>
				</ol>
			</nav>
		</div>
		<!-- End Page Title -->

		<section class="section">
			<div class="row">
				<div class="col-lg-12">

					<div class="card">
						<div class="card-body">
							<h5 class="card-title">Stock Table</h5>

							<div class="card">
								<div class="card-body"><!-- Disabled Backdrop Modal -->
									<!-- Improved Modal -->

									<!-- End Improved Modal -->


								</div>
							</div>
							<!-- Table with stripped rows -->
							<div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
								<div class="datatable-top">
									<div class="datatable-dropdown">
										<label>
											<select id="datatable-selector" class="datatable-selector">
												<option value="10" selected="">ASC</option>
												<option value="15">DES</option>
												<option value="-1">All</option>
											</select>
											entries per page
										</label>
										 
									</div>
									<div class="datatable-search">
  <form method="get" action="{{ path('stock_new') }}">
    <input class="datatable-input" name="searchValue" placeholder="Search..." type="search" title="Search within table">
    <button type="submit" class="btn btn-primary">Search</button>
  </form>
  <button id="resetSearchButton" class="btn btn-secondary mt-3">Reset Search</button>
</div>

									<!-- Display the search results -->
									

									<!-- The rest of your table code -->
								</div>


								<div class="datatable-container">
									<table class="table datatable datatable-table">
										<thead>
											<tr>
												<th data-sortable="true" style="width: 15.805385556915546%;">
													<button class="datatable-sorter">
														<b>Id</b>
													</button>
												</th>
												<th data-sortable="true" style="width: 15%;">
													<button class="datatable-sorter">Nom Produit</button>
												</th>
												<th data-sortable="true" style="width: 15%;">
													<button class="datatable-sorter">Quantité Entrée</button>
												</th>
												<th data-format="YYYY/DD/MM" data-sortable="true" data-type="date" style="width:15%;">
													<button class="datatable-sorter">Quantité Sortie</button>
												</th>
												<th data-sortable="true" class="red" style="width: 15%;">
													<button class="datatable-sorter">Quantité Restante</button>
												</th>
												<th data-sortable="true" class="red" style="width: 15%;">
													<button class="datatable-sorter">Date</button>

												</th>
												<th data-sortable="true" class="red" style="width: 15%;">
													<button class="datatable-sorter">Fournisseur</button>

												</th>
												<th data-sortable="true" class="red" style="width:15%;">
													<button class="datatable-sorter">Actions</button>

												</th>
											</tr>
										</thead>
										<tbody>
										 {% if stockSearch %}
  {# Display search results with a Reset Search button #}
  

  <ul>
    {% for result in stockSearch %}
      <tr data-index="0">
        <td>{{ result.id }}</td>
        <td>{{ result.nomProduit }}</td>
        <td>{{ result.quantiteEntre }}</td>
        <td>{{ result.quantiteSortie }}</td>
        <td>{{ result.quantiteRestante }}</td>
        <td>{{ result.date ? result.date|date('Y-m-d') : 'N/A' }}</td>
        <td>{{ result.fournisseur ? result.fournisseur.getNom() : 'N/A' }}</td>
        <td>
          <button class="btn btn-info rounded-pill">
            <a href="{{ path('stock_show', {'id': result.id}) }}" style="color:white;">Show</a>
          </button>
          <button class="btn btn-success rounded-pill">
            <a href="{{ path('stock_edit', {'id': result.id}) }}" style="color:white;">Edit</a>
          </button>
          <form method="post" action="{{ path('stock_delete', {'id': result.id}) }}" style="display: inline-block;">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ result.id) }}">
            <button type="submit" class="btn btn-danger rounded-pill">Delete</button>
          </form>
        </td>
      </tr>
    {% endfor %}
  </ul>

{% else %}
 
  {# Display a custom alert message when no results are found #}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">No Results Found</h4>
 <div class="icon">
  <i class="bi bi-emoji-frown" style="font-size: 24px;"></i>
  <div class="label"></div>
</div>

<p style="font-size: 18px;">The product you are searching for does not exist for the moment</p>

    <hr>
   
  
  </div>
{% endif %}


<script>
  document.getElementById('resetSearchButton').addEventListener('click', function() {
    window.location.href = '{{ path('stock_new') }}';
  });
</script>

											
											
											
											
											
											{#the add new product khlayel rakez#}
											
											<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#productModal">
												Add New Product
											</button>

											<div class="modal fade" id="productModal" tabindex="-1" aria-hidden="true">
												<div class="modal-dialog">
													<div class="modal-content">
														<div class="modal-header">
															<h5 class="modal-title">Add New Product to Supply Stock</h5>
															<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
														</div>
														<div class="modal-body">
															{{ form_start(form) }}

   <div class="mb-3">
    {{ form_label(form.nom_produit, 'Product Name', {'label_attr': {'class': 'form-label'}}) }}
    {{ form_widget(form.nom_produit, {'attr': {'class': 'form-control', 'placeholder': 'Enter the product name'}}) }}

    {% if form.nom_produit.vars.errors|length > 0 %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Error:</strong>
            {% for error in form.nom_produit.vars.errors %}
                {{ error.message }}
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
</div>

															<div class="mb-3">
																{{ form_label(form.quantite_entre, 'Quantity In') }}
																{{ form_widget(form.quantite_entre, {'attr': {'class': 'form-control'}}) }}
															</div>

															<div class="mb-3">
																{{ form_label(form.quantite_sortie, 'Quantity Out') }}
																{{ form_widget(form.quantite_sortie, {'attr': {'class': 'form-control'}}) }}
															</div>

															<div class="mb-3">
																{{ form_label(form.quantite_restante, 'Remaining Quantity') }}
																{{ form_widget(form.quantite_restante, {'attr': {'class': 'form-control'}}) }}
															</div>

															<div class="mb-3">
																{{ form_label(form.date, 'Date') }}
																{{ form_widget(form.date, {'attr': {'class': 'form-control'}}) }}
															</div>

															<div class="mb-3">
																{{ form_label(form.fournisseur, 'Supplier') }}
																{{ form_widget(form.fournisseur, {'attr': {'class': 'form-select'}}) }}
															</div>

														</div>
														<div class="modal-footer">
															<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
															<button type="submit" class="btn btn-primary">Save</button>
														</div>
														{{ form_end(form) }}
													</div>
												</div>
											</div>
										</tbody>
									</table>
								</div>
								<div class="datatable-bottom">
									<div class="datatable-info">Showing 1 to 10 of 100 entries</div>
									<nav class="datatable-pagination">
										<ul class="datatable-pagination-list">
											<li class="datatable-pagination-list-item datatable-hidden datatable-disabled">
												<button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">‹</button>
											</li>
											<li class="datatable-pagination-list-item datatable-active">
												<button data-page="1" class="datatable-pagination-list-item-link" aria-label="Page 1">1</button>
											</li>
											<li class="datatable-pagination-list-item">
												<button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">2</button>
											</li>
											<li class="datatable-pagination-list-item">
												<button data-page="3" class="datatable-pagination-list-item-link" aria-label="Page 3">3</button>
											</li>
											<li class="datatable-pagination-list-item">
												<button data-page="4" class="datatable-pagination-list-item-link" aria-label="Page 4">4</button>
											</li>
											<li class="datatable-pagination-list-item">
												<button data-page="5" class="datatable-pagination-list-item-link" aria-label="Page 5">5</button>
											</li>
											<li class="datatable-pagination-list-item">
												<button data-page="6" class="datatable-pagination-list-item-link" aria-label="Page 6">6</button>
											</li>
											<li class="datatable-pagination-list-item">
												<button data-page="7" class="datatable-pagination-list-item-link" aria-label="Page 7">7</button>
											</li>
											<li class="datatable-pagination-list-item datatable-ellipsis datatable-disabled">
												<button class="datatable-pagination-list-item-link">…</button>
											</li>
											<li class="datatable-pagination-list-item">
												<button data-page="10" class="datatable-pagination-list-item-link" aria-label="Page 10">10</button>
											</li>
											<li class="datatable-pagination-list-item">
												<button data-page="2" class="datatable-pagination-list-item-link" aria-label="Page 2">›</button>
											</li>
										</ul>
									</nav>
								</div>
							</div>
							<!-- End Table with stripped rows -->

						</div>
					</div>

				</div>
			</div>
		</section>

	</main>
{% endblock %}

templates/stock/new.html.twig
{# templates/stock/new.html.twig #}



{% block title %}New Stock{% endblock %}

{% block body %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h1 class="text-center">Create a new Stock</h1>

        {{ form_start(form) }}

        {{ form_row(form.nom_produit) }}
        {{ form_row(form.quantite_entre) }}
        {{ form_row(form.quantite_sortie) }}
        {{ form_row(form.quantite_restante) }}
        {{ form_row(form.date) }}

        {{ form_label(form.fournisseur) }}
        {{ form_widget(form.fournisseur) }}

        <div class="text-center">
          <button class="btn btn-primary mt-3">Ajouter</button>
        </div>

        {{ form_end(form) }}

        <p class="mt-3 text-center">
          <a href="{{ path('stock_new') }}" class="btn btn-secondary">Back to the list</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

templates/stock/show.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Stock Details{% endblock %}

{% block body %}
    <div style="margin-top: 100px;   display: flex; flex-direction: column; align-items: center;">
        <h1>Stock Details</h1>
        <table border="2" cellpadding="10" cellspacing="10">
            <tr>
                <th>Nom Produit:</th>
                <td>{{ stock.nomProduit }}</td>
            </tr>
            <tr>
                <th>Quantité Entrée:</th>
                <td>{{ stock.quantiteEntre }}</td>
            </tr>
            <tr>
                <th>Quantité Sortie:</th>
                <td>{{ stock.quantiteSortie }}</td>
            </tr>
            <tr>
                <th>Quantité Restante:</th>
                <td>{{ stock.quantiteRestante }}</td>
            </tr>
            <tr>
                <th>Date:</th>
                <td>{{ stock.date ? stock.date|date('Y-m-d') : 'N/A' }}</td>
            </tr>
            <tr>
                <th>Fournisseur:</th>
                <td>{{ stock.fournisseur ? stock.fournisseur.getNom() : 'N/A' }}</td>
            </tr>
        </table>
        <br>
        <a href="{{ path('stock_new') }}">Back to list</a>
    </div>
{% endblock %}